apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dynamo.name }}
  labels:
    app: dynamo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dynamo
  template:
    metadata:
      labels:
        app: dynamo
    spec:
     containers:
     - name: {{ .Values.service.name }}
       image: {{ .Values.dynamo.image }}  
       ports:
       - containerPort: {{ .Values.service.targetport }}
         name: {{ .Values.dynamo.containername }}
      
