apiVersion: v1
kind: Service
metadata:
  #labels: {{ include "helm-charts.labels" | nindent 4 }}
  labels: {{- include "helm-charts.labels" . | nindent 4 }}
  name: {{ .Values.service.name | nindent 4 }}
spec:
  selector:             
    app: {{ .Values.service.name }}
  ports:
  - name: {{ .Values.dynamo.containername }}
    protocol: {{ .values.service.protocol }}
    port: {{ .Values.service.port }}       
    targetPort: {{ .Values.dynamo.containername }}   
