apiVersion: v1
kind: Service
metadata:
  name: dynamo-svc
spec:
  selector:             
    app: {{ .Values.service.name }}
  ports:
  - name: {{ .Values.dynamo.containername }}
    protocol: {{ .Values.service.protocol }}
    port: {{ .Values.service.port }}       
    targetPort: {{ .Values.service.targetport }}
