apiVersion: apps/v1
kind: Deployment
metadata:
  name: complyscan-reactjs-deployment
  labels:
    app: reactjs
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: reactjs
  template:
    metadata:
      labels:
        app: reactjs
    spec:
      containers:
      - name: {{ .Values.frontend.containername }}
        image: {{ .Values.frontend.image }}  
        ports:
        - containerPort: {{ .Values.service.containerport }}
         name: {{ .Values.service.name }}
        env:
        - name: REACT_APP_ENV
          value: "production"
        - name: REACT_APP_CLIENT_ID
          value: "0oa3wdn7nuv4jxwWN5d7"
        - name: REACT_APP_ISSUER
          value: "https://dev-16074608.okta.com/oauth2/default"  
      
