apiVersion: apps/v1
kind: Deployment
metadata:
  name: complyscan-reactjs-deployment
  labels:
    app: reactjs
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: reactjs
  template:
    metadata:
      labels:
        app: reactjs
    spec:
      containers:
      - name: {{ .Values.frontend.containername }}
        image: {{ .Values.frontend.image }}  
        ports:
        - containerPort: {{ .Values.service.containerport }}
         name: {{ .Values.service.name }}
        env:
          {{ - range .Values.examplemap }}
          - name: {{ .name }}
            value: {{ .value }}
           {{ - end }} 
      
