apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:             
    app: reactjs
  ports:
  - name: {{ .Values.service.name }}
    protocol: {{ .Values.service.protocol }}
    port: {{ .Values.service.containerport }}       
    targetPort: {{ .Values.service.name }}   
