name: Deploy based on component
on:
    push: 
     paths: 
        - 'backend-complyscan/**'
    workflow_dispatch: 
permissions:
   id-token: write
   contents: read 

jobs: 
     
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
     - uses: actions/checkout@v3
     - name: Fetch credentials
       uses: aws-actions/configure-aws-credentials@v1
       id: my-role
       with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
          role-session-name: AWSCLI-Session
          role-duration-seconds: 3600
          
     - name: Building Docker image and pushing to ECR
       run: |
         docker build -t complytrust .
         
     - name: login to ECR.
       run: |
         aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.ECR_LOGIN}}
         docker images
         docker tag complytrust:latest ${{secrets.ECR_LOGIN}}/complytrust:latest
         docker push ${{secrets.ECR_LOGIN}}/complytrust:latest
         
     - name: deploying using helm
       run: |
            
            aws s3 ls
            aws eks update-kubeconfig --name ${{secrets.CLUSTER_NAME}} --region ${{secrets.AWS_REGION}}
            cd backend-complyscan
            kubectl get pods
            helm ls
            helm -version
            #helm upgrade --install complytrust ./backend-complyscan
            
            
