name: Deploy based on component
on:
    push: 
     paths: 
        - 'frontend/**'
    workflow_dispatch: 
permissions:
   id-token: write
   contents: read 
env: 
   ECR_REPOSITORY: my-ecr-repository

jobs: 
     
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
     - uses: actions/checkout@v3
     - name: Fetch credentials
       uses: aws-actions/configure-aws-credentials@v1
       id: my-role
       with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
          role-session-name: github-OIDC
          role-duration-seconds: 3600
                
     - name: Login to ECR
       id: login-ecr
       run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_USERNAME }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
       
     
     
     - name: installing using helm
       run: |
            #export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
            aws eks update-kubeconfig --name ${{secrets.CLUSTER_NAME}} --region ${{secrets.AWS_REGION}} --role-arn arn:aws:iam::085395249379:role/cs-clusterrole-eks
            ls -lrt
            cd frontend
            kubectl get pods
            helm upgrade --install COMPLYTRUST ./backend-complyscan
